
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  
  services:
  web:
    build: .
    environment:
      - AFRICASTALKING_USERNAME=sandbox
      - AFRICASTALKING_API_KEY=<YOUR_SANDBOX_API_KEY>
      - ADMIN_EMAIL=admin@example.com
      - DJANGO_EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sil_backend
      POSTGRES_USER: Frank
      POSTGRES_PASSWORD: Reigns3#
    ports:
      - "5432:5432"
